In [2]:
import numpy as np

In [3]:
# Creating a vector from a Python list
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f"Vector v1: {v1}")
print(f"Vector v2: {v2}")
print(f"Shape of v1: {v1.shape}") # (3,) means it has 3 elements

Vector v1: [1 2 3]
Vector v2: [4 5 6]
Shape of v1: (3,)


In [4]:
# Addition and Subtraction
v_add = v1 + v2
v_sub = v1 - v2

# Scalar Multiplication
v_scalar = 3 * v1  # Multiplies every element by 3

# Inner Product (Dot Product)
# Method A: using np.dot()
dot_prod_a = np.dot(v1, v2) 
# Method B: using the @ operator (recommended for readability)
dot_prod_b = v1 @ v2

print(f"v1 + v2: {v_add}")
print(f"v1 - v2: {v_sub}")
print(f"3 * v1:  {v_scalar}")
print(f"Dot Product (v1 . v2): {dot_prod_a}") # 1*4 + 2*5 + 3*6 = 32

v1 + v2: [5 7 9]
v1 - v2: [-3 -3 -3]
3 * v1:  [3 6 9]
Dot Product (v1 . v2): 32


In [6]:
# Creating a 2x3 Matrix (2 rows, 3 columns)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Creating another 2x3 Matrix
B = np.array([
    [7, 8, 9],
    [1, 2, 3]
])

print("Matrix A:\n", A)
print("Shape of A:", A.shape) # Output: (2, 3)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Shape of A: (2, 3)


In [7]:
# Matrix Addition
M_add = A + B

# Matrix Subtraction
M_sub = A - B

# Scalar Multiplication
M_scalar = 0.5 * A

print("A + B:\n", M_add)
print("0.5 * A:\n", M_scalar)

A + B:
 [[ 8 10 12]
 [ 5  7  9]]
0.5 * A:
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [8]:
# --- Matrix-Vector Multiplication ---
# A is (2x3), so the vector must have size 3
x = np.array([1, 1, 1]) 
Ax = A @ x  
# Result shape: (2x3) @ (3,) -> (2,)

print(f"Matrix A:\n{A}")
print(f"Vector x: {x}")
print(f"Product Ax: {Ax}")

# --- Matrix-Matrix Multiplication ---
# Let's create a 3x2 matrix C to multiply with A (2x3)
C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Product: (2x3) @ (3x2) -> (2x2) matrix
AC = A @ C 

print("Matrix C:\n", C)
print("Product A @ C:\n", AC)

Matrix A:
[[1 2 3]
 [4 5 6]]
Vector x: [1 1 1]
Product Ax: [ 6 15]
Matrix C:
 [[1 2]
 [3 4]
 [5 6]]
Product A @ C:
 [[22 28]
 [49 64]]


In [9]:
# 1. Identity Matrix of size 3x3
I = np.eye(3)
print("Identity Matrix (3x3):\n", I)

# 2. Inverse Matrix
# Let's define a square invertible matrix D
D = np.array([
    [1, 2],
    [3, 4]
])

# Calculate Inverse
D_inv = np.linalg.inv(D)

print("Matrix D:\n", D)
print("Inverse of D:\n", D_inv)

# Verification: D @ D_inv should be close to Identity
print("Verification (D @ D_inv):\n", D @ D_inv)

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix D:
 [[1 2]
 [3 4]]
Inverse of D:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Verification (D @ D_inv):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [10]:
# System of equations:
# 2x + y = 8
# 3x + 4y = 18

# Matrix form: A @ x = b
A_sys = np.array([
    [2, 1],
    [3, 4]
])
b_sys = np.array([8, 18])

# Solve for x (which contains x and y)
solution = np.linalg.solve(A_sys, b_sys)

print("Coefficients Matrix A:\n", A_sys)
print("Dependent variables b:", b_sys)
print("Solution [x, y]:", solution)

Coefficients Matrix A:
 [[2 1]
 [3 4]]
Dependent variables b: [ 8 18]
Solution [x, y]: [2.8 2.4]


### Hands-on Challenge 5: Reverse Engineering Grade Weights

**The Scenario:**
The professor has lost the grading syllabus! We have the raw scores for 5 students across 5 different course components (Homework, Quiz, Midterm, Final, and Lab), and we have their calculated **Final Grades**. However, we don't know the **percentage weight** assigned to each component.

Your mission is to use Linear Algebra to "reverse engineer" the grading system and find out how much each component is worth ($x$).

#### The Data
We have the following records for 5 students:

1.  **Student 1:** [90, 80, 85, 90, 95] $\rightarrow$ Final: **88**
2.  **Student 2:** [80, 90, 95, 85, 80] $\rightarrow$ Final: **87**
3.  **Student 3:** [70, 70, 70, 70, 70] $\rightarrow$ Final: **70**
4.  **Student 4:** [60, 100, 80, 90, 100] $\rightarrow$ Final: **83**
5.  **Student 5:** [100, 60, 90, 95, 85] $\rightarrow$ Final: **90**

#### Mathematical Modeling
This problem can be modeled as a system of linear equations in the form $Ax = b$:

* **$A$ (The Coefficient Matrix):** The raw scores of the 5 students (5x5 matrix).
* **$x$ (The Unknowns):** The weights vector $[w_{hw}, w_{quiz}, w_{mid}, w_{final}, w_{lab}]$.
* **$b$ (The Constants):** The final grades vector.

#### Your Task
Use `np.linalg.solve` to calculate the weights ($x$) in the code cell below.